apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/patilvishal1683/chaos_argo_workflow.git
    targetRevision: master
    path: experiments
  destination:
    server: https://kubernetes.default.svc
    namespace: default