apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: step1-templates
  namespace: litmus
spec:
  templates:
    - name: litmus-pod-delete
      inputs:
        parameters:
          - name: chaos-duration
          - name: chaos-interval
          - name: pods-affected-perc
          - name: probe-mode
          - name: experiment-id
          - name: http-probe-url
      resource:
        action: apply
        manifest: |
          apiVersion: litmuschaos.io/v1alpha1
          kind: ChaosEngine
          metadata:
            name: engine-{{inputs.parameters.experiment-id}}
            namespace: {{workflow.parameters.adminModeNamespace}}
          spec:
            appinfo:
              appns: {{workflow.parameters.appNamespace}}
              applabel: "app.kubernetes.io/name={{workflow.parameters.appLabel}}"
              appkind: deployment
            jobCleanUpPolicy: retain
            monitoring: false
            annotationCheck: 'false'
            engineState: 'active'
            chaosServiceAccount: litmus-admin
            components:
              runner:
                nodeSelector:
                  kubernetes.io/os: linux
                  role: "tools"
                tolerations:
                  - key: tools
                    operator: "Equal"
                    value: "true"
                    effect: NoSchedule
            experiments:
              - name: pod-delete
                spec:
                  probe:
                    - name: "check-hello-works"
                      type: "httpProbe"
                      httpProbe/inputs:
                        url: "{{inputs.parameters.http-probe-url}}"
                        insecureSkipVerify: false
                        method:
                          get:
                            criteria: == # supports == & != and oneof operations
                            responseCode: "200"
                      mode: {{inputs.parameters.probe-mode}} # EOT, Continuous
                      runProperties:
                        probeTimeout: 5
                        interval: 5
                        retry: 1
                        probePollingInterval: 2
                  components:
                    nodeSelector:
                      kubernetes.io/os: linux
                      role: "tools"
                    tolerations:
                      - key: tools
                        operator: "Equal"
                        value: "true"
                        effect: NoSchedule
                    statusCheckTimeouts:
                      delay: 15
                      timeout: 30
                    env:
                      - name: TOTAL_CHAOS_DURATION
                        value: "{{inputs.parameters.chaos-duration}}"
                      - name: CHAOS_INTERVAL
                        value: "{{inputs.parameters.chaos-interval}}"
                      - name: PODS_AFFECTED_PERC
                        value: "{{inputs.parameters.pods-affected-perc}}"
                      - name: INSTANCE_ID
                        value: "{{inputs.parameters.experiment-id}}"
                      - name: FORCE
                        value: "false"