apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-

spec:
  entrypoint: main-temp
  arguments:
    parameters:
      - name: message
        value: "Hello"
  templates:
    - name: main-temp
      steps:
      - - name: hello-1
          template: temp-1
          arguments:
            parameters:
              - name: message
                value: "Hello-1"
        - name: hello1b
          template: temp-1
          arguments:
            parameters:
              - name: message
                value: "Hello-1b"

    - name: temp-1
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: ["{{inputs.parameters.message}}"]

