apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-dag

spec:
  entrypoint: main-temp
  templates:
    - name: echo
      inputs:
        parameters:
          - name: message
      container:
        image: alpine:3.7
        command: [echo, "{{inputs.parameters.message}}"]
    - name: main-temp
      dag:
        tasks:
          - name: A
            template: echo
            arguments:
              parameters: [{name: message, value: A}]
          - name: B
            dependencies: [A]
            template: echo
            arguments:
              parameters: [{name: message, value: B}]
          - name: C
            template: echo
            dependencies: [A]
            arguments:
              parameters: [ { name: message, value: C} ]
          - name: D
            dependencies: [B, C]
            template: echo
            arguments:
              parameters: [ { name: message, value: D } ]
