---
apiVersion: v1
kind: Namespace
metadata:
  name: "litmus"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
  name: main-litmus-ingress
  namespace: litmus
spec:
  ingressClassName: nginx
  rules:
  - host: litmusapp.sbx-000094.sause1.bakerhughes.com
    http:
      paths:
      - backend:
          service:
            name: {{ include "litmus-portal.fullname" . }}-frontend-service
            port:
              number: 9091
        path: /?(.*)
        pathType: Prefix
